/** Client-side shop copy. Prices and attacks match server RULES. */
export const WEAPON_CATALOG = [
  {
    id: 'weapon:0001',
    number: 1,
    name: 'Rusty Crowbar',
    type: 'Breaching Tool',
    price: 0,
    attacks: [10, 13, 16, 19],
    flavor: 'Issued with the kit. Bent, rusty, and enough for a cheap door.',
  },
  {
    id: 'weapon:0002',
    number: 2,
    name: 'Glasswire Saw',
    type: 'Wire saw',
    price: 5_000,
    attacks: [20, 22, 25, 27],
    flavor: 'A drawn wire that parts thin steel without a loud bite.',
  },
  {
    id: 'weapon:0003',
    number: 3,
    name: 'Pressure Spike',
    type: 'Door punch',
    price: 8_500,
    attacks: [28, 30, 33, 35],
    flavor: 'A short hydraulic punch for stubborn door skins.',
  },
  {
    id: 'weapon:0004',
    number: 4,
    name: 'Lockpick Set',
    type: 'Infiltration Tool',
    price: 12_000,
    attacks: [36, 40, 44, 47],
    flavor: 'A roll of picks and tension tools. Quiet on a simple lock.',
  },
  {
    id: 'weapon:0005',
    number: 5,
    name: 'Ceramic Lance',
    type: 'Ceramic point',
    price: 22_000,
    attacks: [48, 51, 54, 56],
    flavor: 'A hard ceramic point that finds the seam and stays there.',
  },
  {
    id: 'weapon:0006',
    number: 6,
    name: 'Pulse Ram',
    type: 'Ram',
    price: 32_000,
    attacks: [57, 60, 63, 66],
    flavor: 'Timed impacts that walk a crack across the face of a door.',
  },
  {
    id: 'weapon:0007',
    number: 7,
    name: 'Advanced Drill',
    type: 'Drill',
    price: 40_000,
    attacks: [67, 71, 75, 79],
    flavor: 'A bit that walks through steel. The street hears it.',
  },
  {
    id: 'weapon:0008',
    number: 8,
    name: 'Magnetic Shear',
    type: 'Shear',
    price: 75_000,
    attacks: [80, 83, 86, 89],
    flavor: 'Opposed magnets that peel a plate instead of cutting it.',
  },
  {
    id: 'weapon:0009',
    number: 9,
    name: 'Resonance Driver',
    type: 'Driver',
    price: 95_000,
    attacks: [90, 93, 97, 100],
    flavor: 'Tunes the vault wall until the bolts give up.',
  },
  {
    id: 'weapon:0010',
    number: 10,
    name: 'Thermal Cutter',
    type: 'Cutter',
    price: 125_000,
    attacks: [101, 105, 110, 114],
    flavor: 'A hot tip for plate that shrugs off a drill.',
  },
  {
    id: 'weapon:0011',
    number: 11,
    name: 'Induction Wedge',
    type: 'Wedge',
    price: 190_000,
    attacks: [115, 118, 122, 126],
    flavor: 'An expanding field that forces a gap the door cannot close.',
  },
  {
    id: 'weapon:0012',
    number: 12,
    name: 'Arc Fracture Unit',
    type: 'Arc unit',
    price: 240_000,
    attacks: [127, 131, 135, 139],
    flavor: 'A contained arc that fractures hardened alloys.',
  },
  {
    id: 'weapon:0013',
    number: 13,
    name: 'Vault Breaker',
    type: 'Breaker',
    price: 350_000,
    attacks: [140, 145, 150, 155],
    flavor: 'A frame and a ram sized for a bank door.',
  },
  {
    id: 'weapon:0014',
    number: 14,
    name: 'Graviton Press',
    type: 'Press',
    price: 500_000,
    attacks: [156, 161, 166, 171],
    flavor: 'Crushes a locking stack until the pins no longer meet.',
  },
  {
    id: 'weapon:0015',
    number: 15,
    name: 'Seismic Lance',
    type: 'Lance',
    price: 750_000,
    attacks: [172, 178, 184, 190],
    flavor: 'A directed shock that travels through the vault instead of the door.',
  },
] as const

export type CatalogWeapon = (typeof WEAPON_CATALOG)[number]
